version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
stages:
  - stage:
    name: build
    displayName: 构建
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 22
        commands:
          - npm install
          - npx electron-vite build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./out
triggers:
  push:
    branches:
      exclude:
        - master
      include:
        - main
